apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/noorissebar/dealership:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: ibmcloud-registry-secret
