# Generated by Django 5.0.7 on 2024-07-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dealership', models.IntegerField()),
                ('review', models.TextField()),
                ('purchase', models.BooleanField()),
                ('purchase_date', models.DateField()),
                ('car_make', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('car_year', models.IntegerField()),
            ],
        ),
    ]
