# Generated by Django 5.2.1 on 2025-05-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmake',
            options={'verbose_name': 'Car Make', 'verbose_name_plural': 'Car Makes'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='dealer_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
