# Generated by Django 5.1.2 on 2024-10-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carmake",
            name="country_of_origin",
        ),
    ]
