# Generated by Django 4.2.7 on 2024-02-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="dealer_id",
            field=models.IntegerField(
                help_text="ID of the dealer this model belongs to"
            ),
        ),
    ]
