# Generated by Django 5.1.2 on 2024-10-16 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0002_remove_carmake_country_of_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(2015),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
